### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by rodneytamblyn** [trevordevore/levurehelper-dropDMG#2]
Hi Trevor,

I've setup dropDMG app, Levure helper and updated my app.yml file.  I also added dropDMG into the helpers section of app.yml which I assume is also required?

To confirm, when I run (for example):
```
levurePackageApplication "beta"
```
... it should also as a post packaging task create the DMG file as well?

Tried setting a breakpoint in the dropDMG_packager script but it doesn't drop into the debugger, which I guess means it is still not configured right.

![image](https://user-images.githubusercontent.com/1562956/186385331-0bac9cfc-254c-4dfb-ac50-1b53297a1a30.png)

**Comment by trevordevore** [comment]
@rodneytamblyn in the screenshot it looks like your indentation is off in the YAML file. Line up the dropdmg helper line with the line above it and then it should work.

**Comment by rodneytamblyn** [comment]
Thanks Trevor, working now.
